### PR TITLE
Fixed how configuration is loaded to be the Bukkit API supported calls.

### PR DESCRIPTION
**Pull request by Majforce**
Clean up some code.

No new features.

---

Hey NiftyMonkey,

Majforce here with the pull request we talked about. It should be working with the newest Bukkit and Minecraft versions. 

Let me know how it goes.
-Majforce

### CODE REVIEW

**Comment by niftymonkey** [comment]
What version of the Permissions plugin did you use to build against? (if any)

**Comment by Majforce** [comment]
I saw you were using PermissionsBukkit so, I just continued to use that. Is that okay?

**Comment by niftymonkey** [comment]
Yeah that's cool, just was curious if you left that legacy Permissions-3.1.3 jar as the dependency or if you moved up to a different version.

Also, just curious, did you use maven to build?  Looks like the test cases are breaking when I try to build.

**Comment by niftymonkey** [comment]
Oh, lastly, which version of Craftbukkit did you run this against?  Only asking because the latest reccomended build for craftbukkit is still 1.1 based, whereas the client is 1.2.3 ... 1.2 clients are incompatible with 1.1 servers.

**Comment by Majforce** [comment]
I was testing is against Craftbukkit Beta 1.2.3-R0.2 (#2060). I have a server running it now with 1.2 clients and all seems to be good. NiftyWarp is working great too.

No, I didn't built it with Maven. Just exported the Jar using Eclipse and tested directly.

**Comment by niftymonkey** [comment]
Ah, ok ... well I just tried it with that same Craftbukkit build you listed.  Seems to work.  I also made some changes to get the unit tests to build.  And also fixed the pom version and plugin version.  Should be ready to go here in a bit.

Did you test any kinda permissions in-game?

**Comment by Majforce** [comment]
I didn't do any extensive tests. I just had a user try to use /nwversion and it failed so in theory it should be good. (I don't allow users to see that).

**Comment by niftymonkey** [comment]
Merged in via a separate branch, then merged to master.  Tagged as 1.4.  Thanks for working this.

**Comment by Majforce** [comment]
My pleasure. I actually tagged this release as version 1.3.2 in the plugin.yml file. Would you like to change it or leave it for now?

**Pull request merged**
